In [2]:
import pandas as pd
import numpy as np

In [3]:
# Load Dataset.
df = pd.read_csv("../data/credit_risk.csv")
df.head()

,person_age,person_income,person_home_ownership,person_emp_length,loan_intent,loan_grade,loan_amnt,loan_int_rate,loan_status,loan_percent_income,cb_person_default_on_file,cb_person_cred_hist_length
0,22,59000,RENT,123.0,PERSONAL,D,35000,16.02,1,0.59,Y,3
1,21,9600,OWN,5.0,EDUCATION,B,1000,11.14,0,0.10,N,2
2,25,9600,MORTGAGE,1.0,MEDICAL,C,5500,12.87,1,0.57,N,3
3,23,65500,RENT,4.0,MEDICAL,C,35000,15.23,1,0.53,N,2
4,24,54400,RENT,8.0,MEDICAL,C,35000,14.27,1,0.55,Y,4

In [4]:
# Dataset shape.
print(df.shape)

# Column information.
df.info()

(32581, 12)
<class 'pandas.DataFrame'>
RangeIndex: 32581 entries, 0 to 32580
Data columns (total 12 columns):
 #   Column                      Non-Null Count  Dtype
---  ------                      --------------  -----
 0   person_age                  32581 non-null  int64
 1   person_income               32581 non-null  int64
 2   person_home_ownership       32581 non-null  str
 3   person_emp_length           31686 non-null  float64
 4   loan_intent                 32581 non-null  str
 5   loan_grade                  32581 non-null  str
 6   loan_amnt                   32581 non-null  int64
 7   loan_int_rate               29465 non-null  float64
 8   loan_status                 32581 non-null  int64
 9   loan_percent_income         32581 non-null  float64
 10  cb_person_default_on_file   32581 non-null  str
 11  cb_person_cred_hist_length  32581 non-null  int64
dtypes: float64(3), int64(5), str(4)
memory usage: 3.0 MB

In [5]:
# Missing values.
print(df.isnull().sum())

(df.isnull().sum() / len(df) * 100).round(2)

person_age                       0
person_income                    0
person_home_ownership            0
person_emp_length              895
loan_intent                      0
loan_grade                       0
loan_amnt                        0
loan_int_rate                 3116
loan_status                      0
loan_percent_income              0
cb_person_default_on_file        0
cb_person_cred_hist_length       0
dtype: int64

person_age                    0.00
person_income                 0.00
person_home_ownership         0.00
person_emp_length             2.75
loan_intent                   0.00
loan_grade                    0.00
loan_amnt                     0.00
loan_int_rate                 9.56
loan_status                   0.00
loan_percent_income           0.00
cb_person_default_on_file     0.00
cb_person_cred_hist_length    0.00
dtype: float64

In [6]:
# duplcated rows.
df.duplicated().sum()

np.int64(165)

In [7]:
# Numericals column.
df.describe()

,person_age,person_income,person_emp_length,loan_amnt,loan_int_rate,loan_status,loan_percent_income,cb_person_cred_hist_length
count,32581.000000,3.258100e+04,31686.000000,32581.000000,29465.000000,32581.000000,32581.000000,32581.000000
mean,27.734600,6.607485e+04,4.789686,9589.371106,11.011695,0.218164,0.170203,5.804211
std,6.348078,6.198312e+04,4.142630,6322.086646,3.240459,0.413006,0.106782,4.055001
min,20.000000,4.000000e+03,0.000000,500.000000,5.420000,0.000000,0.000000,2.000000
25%,23.000000,3.850000e+04,2.000000,5000.000000,7.900000,0.000000,0.090000,3.000000
50%,26.000000,5.500000e+04,4.000000,8000.000000,10.990000,0.000000,0.150000,4.000000
75%,30.000000,7.920000e+04,7.000000,12200.000000,13.470000,0.000000,0.230000,8.000000
max,144.000000,6.000000e+06,123.000000,35000.000000,23.220000,1.000000,0.830000,30.000000

In [8]:
# Categorical columns.
categorical_columns = df.select_dtypes(
    include="object"
).columns.tolist()

categorical_columns

C:\Users\kush6\AppData\Local\Temp\ipykernel_10304\1199309222.py:2: Pandas4Warning: For backward compatibility, 'str' dtypes are included by select_dtypes when 'object' dtype is specified. This behavior is deprecated and will be removed in a future version. Explicitly pass 'str' to `include` to select them, or to `exclude` to remove them and silence this warning.
See https://pandas.pydata.org/docs/user_guide/migration-3-strings.html#string-migration-select-dtypes for details on how to write code that works with pandas 2 and 3.
  categorical_columns = df.select_dtypes(

['person_home_ownership',
 'loan_intent',
 'loan_grade',
 'cb_person_default_on_file']

In [9]:
# Unique values.
for column in categorical_columns:
    print(f"\n{column}")
    print(df[column].value_counts(dropna=False))

person_home_ownership
person_home_ownership
RENT        16446
MORTGAGE    13444
OWN          2584
OTHER         107
Name: count, dtype: int64

loan_intent
loan_intent
EDUCATION            6453
MEDICAL              6071
VENTURE              5719
PERSONAL             5521
DEBTCONSOLIDATION    5212
HOMEIMPROVEMENT      3605
Name: count, dtype: int64

loan_grade
loan_grade
A    10777
B    10451
C     6458
D     3626
E      964
F      241
G       64
Name: count, dtype: int64

cb_person_default_on_file
cb_person_default_on_file
N    26836
Y     5745
Name: count, dtype: int64

In [10]:
# Target Distribution.
print(df["loan_status"].value_counts())

# Target Distribution in Percentage.
df["loan_status"].value_counts(normalize=True).mul(100).round(2)

loan_status
0    25473
1     7108
Name: count, dtype: int64

loan_status
0    78.18
1    21.82
Name: proportion, dtype: float64

In [11]:
# Target + Features Relationship.

df.groupby("loan_status")[
    [
        "person_age",
        "person_income",
        "loan_amnt",
        "loan_int_rate",
        "loan_percent_income",
        "cb_person_cred_hist_length"
    ]
].mean().round(2)

,person_age,person_income,loan_amnt,loan_int_rate,loan_percent_income,cb_person_cred_hist_length
loan_status,,,,,,
0,27.81,70804.36,9237.46,10.44,0.15,5.84
1,27.47,49125.65,10850.50,13.06,0.25,5.69

In [ ]:
# Person Loan status whose age is greater than 100.
df[df["person_age"] > 100][
    ["person_age", "loan_status"]
]

       person_age  loan_status
81            144            0
183           144            0
575           123            0
747           123            0
32297         144            0

In [ ]:
# Person who was employed more than 50 years.
df[df["person_emp_length"] > 50][
    ["person_age", "person_emp_length", "loan_status"]
]

     person_age  person_emp_length  loan_status
0            22              123.0            1
210          21              123.0            0

In [ ]:
# Person age, person_income whose income is greater than 500000.
df[df["person_income"] > 500000][
    ["person_age", "person_income", "loan_status"]
]

       person_age  person_income  loan_status
17833          32        1200000            0
17834          34         948000            0
17840          35         648000            1
17846          30         504000            0
18635          31         636000            0
18917          35         510000            0
21462          33         612000            0
21958          34         564000            0
23429          31         552000            0
23431          30         648000            0
25714          32         703800            1
27798          32         572400            0
27877          30         522000            0
27881          28         604000            1
27882          31         741600            0
27883          32         750000            0
27884          35         762000            0
28253          35         762000            0
28633          33         612000            0
28770          28         604000            1
29119          36        1200000            0
29120          40        1200000            0
29121          50         900000            0
29122          36         900000            0
29126          39         708000            0
29127          44         584800            1
29128          36         700000            0
29129          40         540600            1
29345          42         889000            0
29514          37         528000            0
30049          42        2039784            0
30536          37         780000            0
31911          40         550000            0
31912          40         550000            0
31913          37         600000            0
31915          42         600000            0
31916          43         780000            0
31918          37         800000            0
31919          36         828000            0
31921          37         900000            0
31922          47        1362000            0
31924          44        1440000            0
32037          36         828000            0
32070          37         780000            0
32291          42         600000            0
32297         144        6000000            0
32298          58         900000            0
32300          51         667680            0
32497          63        1782000            0
32543          52         720000            0
32544          58         780000            0
32546          60        1900000            0
32551          58         780000            0

In [ ]:
# Duplicated data.
df[df.duplicated(keep=False)].head(20)

,person_age,person_income,person_home_ownership,person_emp_length,loan_intent,loan_grade,loan_amnt,loan_int_rate,loan_status,loan_percent_income,cb_person_default_on_file,cb_person_cred_hist_length
14,23,115000,RENT,2.0,EDUCATION,A,35000,7.90,0,0.30,N,4
238,22,183000,MORTGAGE,3.0,EDUCATION,A,1000,NaN,0,0.01,N,2
252,24,85000,RENT,5.0,MEDICAL,B,25000,10.62,0,0.29,N,4
591,26,20000,MORTGAGE,5.0,MEDICAL,A,4800,5.99,0,0.24,N,3
740,21,21600,OWN,NaN,VENTURE,A,7125,6.99,0,0.33,N,3
817,22,22000,OWN,1.0,DEBTCONSOLIDATION,D,8500,15.05,0,0.39,N,4
920,26,50000,RENT,10.0,PERSONAL,B,18950,NaN,1,0.38,N,3
1094,22,24449,OWN,2.0,VENTURE,B,1800,11.89,0,0.07,N,4
1142,25,60000,RENT,3.0,PERSONAL,A,17000,6.91,0,0.28,N,2
1453,23,20400,RENT,2.0,MEDICAL,A,1200,7.90,0,0.06,N,2
1584,24,35000,RENT,9.0,EDUCATION,A,1500,NaN,0,0.04,N,3
1597,24,39000,RENT,8.0,MEDICAL,D,1500,15.62,0,0.04,Y,3
1675,21,28692,MORTGAGE,5.0,EDUCATION,B,3000,10.75,0,0.10,N,2
1778,21,20000,RENT,0.0,MEDICAL,A,2000,NaN,0,0.10,N,3
2431,21,15600,RENT,0.0,MEDICAL,A,2800,7.40,1,0.18,N,4
2471,24,10000,RENT,8.0,PERSONAL,A,3000,7.90,1,0.30,N,3
2498,21,18000,RENT,0.0,DEBTCONSOLIDATION,A,3000,7.90,1,0.17,N,2
2499,22,32400,MORTGAGE,1.0,DEBTCONSOLIDATION,A,5500,NaN,0,0.17,N,2
2633,24,33321,OWN,4.0,VENTURE,C,12250,13.11,0,0.37,Y,4
3165,21,36000,MORTGAGE,5.0,MEDICAL,B,1000,12.42,0,0.03,N,2

In [ ]:
# Loan status on the basis of person_home_ownership.
pd.crosstab(
    df["person_home_ownership"],
    df["loan_status"],
    normalize="index"
).round(3)

loan_status                0      1
person_home_ownership
MORTGAGE               0.874  0.126
OTHER                  0.692  0.308
OWN                    0.925  0.075
RENT                   0.684  0.316

In [ ]:
# Loan status on the basis of loan_intent.
pd.crosstab(
    df["loan_intent"],  
    df["loan_status"],
    normalize="index"
).round(3)

loan_status            0      1
loan_intent
DEBTCONSOLIDATION  0.714  0.286
EDUCATION          0.828  0.172
HOMEIMPROVEMENT    0.739  0.261
MEDICAL            0.733  0.267
PERSONAL           0.801  0.199
VENTURE            0.852  0.148

In [ ]:
# Loan status on the basis of loan_grade.
pd.crosstab(
    df["loan_grade"],
    df["loan_status"],
    normalize="index"
).round(3)

loan_status      0      1
loan_grade
A            0.900  0.100
B            0.837  0.163
C            0.793  0.207
D            0.410  0.590
E            0.356  0.644
F            0.295  0.705
G            0.016  0.984

In [ ]:
# Loan status on the basis of cb_person_default_on_file.
pd.crosstab(
    df["cb_person_default_on_file"],
    df["loan_status"],
    normalize="index"
).round(3)

loan_status                    0      1
cb_person_default_on_file
N                          0.816  0.184
Y                          0.622  0.378